# Generated by Django 2.1.5 on 2019-01-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('size', models.IntegerField()),
                ('date_entered', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
