# Generated by Django 2.1.5 on 2019-01-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190126_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='heigth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
